name: linting, testing, building
on:
  pull_request:
    branches: [ main ]
jobs:
  Pipeline:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        run: npm install --include=dev

      - name: build production project
        run: npm run build:prod

      - name: linting
        run: |
          npm run lint:ts
          npm run lint:scss
        if: always()

      - name: unit testing
        run: npm run test:unit
        if: always()

      - name: build storybook
        run: npm run storybook:build
        if: always()

      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()
